project:
  type: default
  render:
    - main.qmd
    - README.qmd
title: >-
  Detecting adverse high-order drug combinations from individual case safety reports using computational statistics on disproportionality measures
author:
  - name: Jules Bangard
    corresponding: true
    email: jules.bangard@math.unistra.fr
    url: https://bangard.xyz
    orcid: 0009-0007-4670-7860
    affiliations:
      - name: Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg et CNRS 7 rue René-Descartes, 67000 Strasbourg, France
        url: https://irma.math.unistra.fr/
  - name: Einar Holsbø
    email: einar.j.holsbo@uit.no
    url: https://einar.sh/
    orcid: 0000-0002-9728-2088
    affiliations:
      - name: Faculty of Science and Technology, UiT-The Arctic University of Norway, PO, Box 6050 Stakkevollan, N-9037 Tromsø, Norway
        url: https://en.uit.no/startsida
  - name: Kristian Svendsen
    email: kristian.svendsen@uit.no
    url: https://en.uit.no/ansatte/kristian.svendsen
    orcid: 0000-0003-3481-3539
    affiliations:
      - name: Faculty of Health Sciences, UiT the Arctic University of Norway, Tromsø, Norway
        url: https://en.uit.no/startsida
  - name: Vittorio Perduca
    email: vittorio.perduca@parisdescartes.fr
    url: https://helios2.mi.parisdescartes.fr/~vperduca/
    orcid: 0000-0003-0339-0473
    affiliations:
      - name: CNRS, MAP5, Université Paris Cité, F-75006 Paris, France
        url: https://map5.mi.parisdescartes.fr/
  - name: Étienne Birmelé
    email: birmele@unistra.fr
    url: https://irma.math.unistra.fr/~birmele/
    orcid: 0000-0002-6996-4014
    affiliations:
      - name: Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg et CNRS 7 rue René-Descartes, 67000 Strasbourg, France
        url: https://irma.math.unistra.fr/
date: 2026-07-15
date-modified: last-modified
description: |
  Adverse drug combination detection using individual case safety reports
abstract: >+
  Adverse drug reactions linked to the intake of drug combinations are a critical concern
  in pharmacovigilance, particularly as the controlled environment of clinical
  trials often lacks the scale and diversity to detect rare events involving multiple
  medications. While spontaneous reporting systems provide the necessary
  breadth for post-market surveillance, identifying overrepresented drug cocktails
  within such large-scale data remains a significant computational challenge. This
  study introduces a computational framework for the detection of drug cocktails
  associated with adverse events, leveraging disproportionality analysis
  on individual case safety reports. By integrating the Anatomical Therapeutic
  Chemical classification, the framework extends beyond individual drugs to capture
  hierarchical pharmacological relationships, enabling exploration of the space
  of drug combinations beyond pairwise analysis. To address biases inherent in
  existing disproportionality measures, we employ a hypergeometric risk metric,
  while a Markov Chain Monte Carlo algorithm provides robust empirical p-value
  estimation for the risk associated with cocktails. A genetic algorithm further
  facilitates efficient identification of high-risk drug cocktails. A post-treatment step
  based on penalized logistic regression allows distinguishing true pharmacological
  interactions from combined individual effects for cocktails of any size. Validation
  on synthetic and FDA Adverse Event Reporting System data demonstrates
  the method’s efficacy in detecting established drugs and drug combinations
  associated with myopathy-related adverse events. Implemented as an R package,
  this framework offers a reproducible, scalable tool for post-market drug safety
  surveillance.
keywords: [Disproportionality Analysis, Drug-Combinations, Drug-Interactions, Genetic Algorithm, Markov
  Chain Monte Carlo, Pharmacovigilance, Spontaneous Reporting Systems]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/7e54-2z98"
  publisher: "French Statistical Society"
  issn: "2824-7795"
  url: "https://computo-journal.org/published-202605-bangard-adverse/"
  pdf-url: "https://computo-journal.org/published-202605-bangard-adverse/main.pdf"
google-scholar: true
related-identifiers:
  - relation: IsVersionOf
    type: arXiv
    identifier: "2504.00646"
bibliography: references.bib
github-user: computorg
repo: "published-202605-bangard-adverse"
status: published
license: CC-BY-4.0
format:
  computo-html: default
  computo-pdf: default
